# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jackb}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Damien MATHIEU"]
  s.date = %q{2010-06-19}
  s.description = %q{Takes some content and parses it depending of the format your specify (HTML or Markdown)}
  s.email = %q{42@dmathieu.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "README.md",
     "Rakefile",
     "VERSION",
     "jackb.gemspec",
     "lib/jackb.rb",
     "lib/jackb/highlight.rb",
     "lib/jackb/html.rb",
     "lib/jackb/markdown.rb",
     "spec/lib/highlight_spec.rb",
     "spec/lib/html_spec.rb",
     "spec/lib/jackb_spec.rb",
     "spec/lib/markdown_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dmathieu/jackb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Is your content in HTML or Markdown ?}
  s.test_files = [
    "spec/lib/highlight_spec.rb",
     "spec/lib/html_spec.rb",
     "spec/lib/jackb_spec.rb",
     "spec/lib/markdown_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdiscount>, [">= 1.6.3.2"])
      s.add_runtime_dependency(%q<open4>, [">= 1.0.1"])
      s.add_runtime_dependency(%q<albino>, [">= 1.0"])
    else
      s.add_dependency(%q<rdiscount>, [">= 1.6.3.2"])
      s.add_dependency(%q<open4>, [">= 1.0.1"])
      s.add_dependency(%q<albino>, [">= 1.0"])
    end
  else
    s.add_dependency(%q<rdiscount>, [">= 1.6.3.2"])
    s.add_dependency(%q<open4>, [">= 1.0.1"])
    s.add_dependency(%q<albino>, [">= 1.0"])
  end
end

